/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import clases.Util;
import clases.Conexion;
import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JTable;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author ALEX
 */
public class Cancelados_tabla extends javax.swing.JDialog {
    
    private DefaultTableModel model = new DefaultTableModel();

    /**
     * Creates new form Cancelados_tabla
     */
    public Cancelados_tabla(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setSize(550,510);
        setTitle("TE cancelados - " + Login.user);
        setLocationRelativeTo(null);
        
        jTextField_buscar.setText("");
        jComboBox_campos.setSelectedItem("Todos");
        
        jTable_servicios_cxx = new JTable(model);
        jScrollPane1.setViewportView(jTable_servicios_cxx);
        
        model.addColumn("");
        model.addColumn("DESCRIPCION");
        model.addColumn("TE");
        model.addColumn("RESERVADO");
        model.addColumn("USUARIO");
        
        Color myColorFondo = new Color(204, 204, 204);
        Color myColorFuente = new Color(0, 0, 115);
        jTable_servicios_cxx.setBackground(myColorFondo);
        jTable_servicios_cxx.setForeground(myColorFuente);
        
        Filtrar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField_buscar = new javax.swing.JTextField();
        jComboBox_campos = new javax.swing.JComboBox<>();
        jButton_filtrar = new javax.swing.JButton();
        jLabel_footer = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_servicios_cxx = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("TABLA SERVICIOS CANCELADOS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 43, -1, -1));

        jTextField_buscar.setBackground(new java.awt.Color(204, 204, 204));
        jTextField_buscar.setForeground(new java.awt.Color(0, 0, 115));
        jTextField_buscar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        jTextField_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_buscarActionPerformed(evt);
            }
        });
        jTextField_buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_buscarKeyPressed(evt);
            }
        });
        jPanel1.add(jTextField_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 100, 30));

        jComboBox_campos.setBackground(new java.awt.Color(100, 100, 100));
        jComboBox_campos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "TE", "Fecha_reservado" }));
        jComboBox_campos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox_camposKeyPressed(evt);
            }
        });
        jPanel1.add(jComboBox_campos, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, 100, 30));

        jButton_filtrar.setBackground(new java.awt.Color(153, 153, 153));
        jButton_filtrar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_filtrar.setText("Filtrar");
        jButton_filtrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_filtrarActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_filtrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 415, 80, 30));

        jLabel_footer.setText("© Realizado por atstincer");
        jPanel1.add(jLabel_footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 450, 150, 20));

        jTable_servicios_cxx.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTable_servicios_cxx.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable_servicios_cxx.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_servicios_cxx.setCellSelectionEnabled(true);
        jTable_servicios_cxx.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(jTable_servicios_cxx);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 85, 500, 300));

        jLabel2.setText("- solo aparecen TE's reservados desde un inicio como cancelados.");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_buscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_buscarActionPerformed

    private void jTextField_buscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_buscarKeyPressed
        // TODO add your handling code here:
        if (evt.getExtendedKeyCode() == KeyEvent.VK_ENTER) {
            Filtrar();
        }
    }//GEN-LAST:event_jTextField_buscarKeyPressed

    private void jButton_filtrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_filtrarActionPerformed
        // TODO add your handling code here:
        Filtrar();
    }//GEN-LAST:event_jButton_filtrarActionPerformed

    private void jComboBox_camposKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox_camposKeyPressed
        // TODO add your handling code here:
        if(evt.getExtendedKeyCode() == KeyEvent.VK_ENTER){
            Filtrar();
        }
    }//GEN-LAST:event_jComboBox_camposKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cancelados_tabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cancelados_tabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cancelados_tabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cancelados_tabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Cancelados_tabla dialog = new Cancelados_tabla(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_filtrar;
    private javax.swing.JComboBox<String> jComboBox_campos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_footer;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_servicios_cxx;
    private javax.swing.JTextField jTextField_buscar;
    // End of variables declaration//GEN-END:variables


    private void Filtrar(){
        String buscar = jTextField_buscar.getText();
        String campo = jComboBox_campos.getSelectedItem().toString();
        String query = "";
        
        if(!campo.equals("Todos") && buscar.equals("")){
            JOptionPane.showMessageDialog(null,"Debe proporcionar la información a buscar.");
            return;
        }
        
        if(campo.equals("Todos")){
            jTextField_buscar.setText("");
            query = "select Id_servicio, Descripcion, TE_alojamiento, Reservado_fecha, Reservado_por, TE_traslado "
                    + "from servicios where Descripcion = 'CANCELADO' and CXX = 'SI'";
        } else if(campo.equals("TE")){
            query = "select Id_servicio, Descripcion, TE_alojamiento, Reservado_fecha, Reservado_por, TE_traslado "
                    + "from servicios where Descripcion = 'CANCELADO' and CXX = 'SI' and "
                    + "(TE_alojamiento = '" + buscar + "' or TE_traslado = '" + buscar + "')";
        }else if(campo.equals("Fecha_reservado")){
            if(Util.ValidDate(buscar)){
                query = "select Id_servicio, Descripcion, TE_alojamiento, Reservado_fecha, Reservado_por, TE_traslado "
                        + "from servicios where Descripcion = 'CANCELADO' and CXX = 'SI' and "
                        + "Reservado_fecha = '" + buscar + "'";
            }else{
                JOptionPane.showMessageDialog(null,"Lo sentimos. La operación no se puede realizar.\n"
                        + "Debe introducir la fecha deseada en el formato 'dia/mes/año'.");
                return;
            }            
        }
        
        Util.VaciarTabla(model);
        
        try{
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement(query);
            
            ResultSet rs = pst.executeQuery();
            
            while(rs.next()){
                Object[] fila_rs = new Object[6];
                Object[] fila = new Object[5];
                
                for(int i=0; i<fila_rs.length; i++){//llenando fila_rs
                    fila_rs[i] = rs.getString(i+1);
                }
                
                if(!fila_rs[2].equals("")){//si TE_alojamiento
                    for(int i=0; i<fila.length; i++){
                        fila[i] = fila_rs[i];
                    }
                    model.addRow(fila);
                }
                
                if(!fila_rs[5].equals("")){//si TE_traslado
                    for(int i=0; i<fila.length; i++){
                        fila[i] = fila_rs[i];
                    }
                    fila[2] = fila_rs[5];
                    model.addRow(fila);
                }                
            }
            cn.close();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,"Error: " + e.getMessage().toString());
        }        
    }  
}