/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import clases.Conexion;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.*;

/**
 *
 * @author ALEX
 */
public class Clientes_agregar extends javax.swing.JFrame {

    /**
     * Creates new form Clientes_agregar
     */
    public Clientes_agregar() {
        initComponents();
        setSize(370, 450);
        setResizable(false);
        setLocationRelativeTo(null);
        setTitle("Agregar clientes - " + Login.user);
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/Icon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField_nombre = new javax.swing.JTextField();
        jTextField_apellido = new javax.swing.JTextField();
        jTextField_nacionalidad = new javax.swing.JTextField();
        jTextField_telefono = new javax.swing.JTextField();
        jTextField_cell = new javax.swing.JTextField();
        jTextField_mail = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_observaciones = new javax.swing.JTextArea();
        jButton_agregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("INFORMACION GENERAL");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 45, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Nombre");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Apellido");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Nacionalidad");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 155, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Teléfono");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Celular");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 285, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Mail");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 155, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Observaciones");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, -1, -1));

        jTextField_nombre.setBackground(new java.awt.Color(204, 204, 204));
        jTextField_nombre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_nombre.setForeground(new java.awt.Color(0, 0, 115));
        jTextField_nombre.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        jPanel1.add(jTextField_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 107, 100, 25));

        jTextField_apellido.setBackground(new java.awt.Color(204, 204, 204));
        jTextField_apellido.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_apellido.setForeground(new java.awt.Color(0, 0, 115));
        jTextField_apellido.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        jPanel1.add(jTextField_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 107, 100, 25));

        jTextField_nacionalidad.setBackground(new java.awt.Color(204, 204, 204));
        jTextField_nacionalidad.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_nacionalidad.setForeground(new java.awt.Color(0, 0, 115));
        jTextField_nacionalidad.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        jTextField_nacionalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_nacionalidadActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField_nacionalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 172, 100, 25));

        jTextField_telefono.setBackground(new java.awt.Color(204, 204, 204));
        jTextField_telefono.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_telefono.setForeground(new java.awt.Color(0, 0, 115));
        jTextField_telefono.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        jTextField_telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_telefonoActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 237, 100, 25));

        jTextField_cell.setBackground(new java.awt.Color(204, 204, 204));
        jTextField_cell.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_cell.setForeground(new java.awt.Color(0, 0, 115));
        jTextField_cell.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        jTextField_cell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_cellActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField_cell, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 302, 100, 25));

        jTextField_mail.setBackground(new java.awt.Color(204, 204, 204));
        jTextField_mail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_mail.setForeground(new java.awt.Color(0, 0, 115));
        jTextField_mail.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        jTextField_mail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_mailActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField_mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 172, 165, 25));

        jTextArea_observaciones.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea_observaciones.setColumns(20);
        jTextArea_observaciones.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jTextArea_observaciones.setForeground(new java.awt.Color(0, 0, 115));
        jTextArea_observaciones.setRows(5);
        jTextArea_observaciones.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        jScrollPane1.setViewportView(jTextArea_observaciones);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 237, -1, 89));

        jButton_agregar.setBackground(new java.awt.Color(153, 153, 153));
        jButton_agregar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_agregar.setText("Agregar");
        jButton_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_agregarActionPerformed(evt);
            }
        });
        jButton_agregar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton_agregarKeyPressed(evt);
            }
        });
        jPanel1.add(jButton_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 368, 100, 35));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_nacionalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_nacionalidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_nacionalidadActionPerformed

    private void jTextField_telefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_telefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_telefonoActionPerformed

    private void jTextField_cellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_cellActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_cellActionPerformed

    private void jTextField_mailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_mailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_mailActionPerformed

    private void jButton_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_agregarActionPerformed
        // TODO add your handling code here:
        Agregar();
    }//GEN-LAST:event_jButton_agregarActionPerformed

    private void jButton_agregarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton_agregarKeyPressed
        // TODO add your handling code here:
         if(evt.getExtendedKeyCode()==KeyEvent.VK_ENTER){
            Agregar();
        }
    }//GEN-LAST:event_jButton_agregarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clientes_agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clientes_agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clientes_agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clientes_agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Clientes_agregar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_agregar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea_observaciones;
    private javax.swing.JTextField jTextField_apellido;
    private javax.swing.JTextField jTextField_cell;
    private javax.swing.JTextField jTextField_mail;
    private javax.swing.JTextField jTextField_nacionalidad;
    private javax.swing.JTextField jTextField_nombre;
    private javax.swing.JTextField jTextField_telefono;
    // End of variables declaration//GEN-END:variables

    public void Limpiar() {
        jTextField_nombre.setText("");
        jTextField_apellido.setText("");
        jTextField_nacionalidad.setText("");
        jTextField_telefono.setText("");
        jTextField_cell.setText("");
        jTextField_mail.setText("");
        jTextArea_observaciones.setText("");
    }
    
    public void Agregar(){
         String nombre = jTextField_nombre.getText().trim();
        String apellido = jTextField_apellido.getText().trim();
        String telefono = jTextField_telefono.getText().trim();
        String cell = jTextField_cell.getText().trim();
        String nacionalidad = jTextField_nacionalidad.getText().trim();
        String mail = jTextField_mail.getText().trim();
        String observaciones = jTextArea_observaciones.getText().trim();

        if (!nombre.equals("") && !apellido.equals("")) {
            try {
                Connection cn = Conexion.conectar();
                PreparedStatement pst = cn.prepareStatement("insert into Clientes values (?,?,?,?,?,?,?,?)");

                pst.setInt(1, 0);
                pst.setString(2, nombre);
                pst.setString(3, apellido);
                pst.setString(4, nacionalidad);
                pst.setString(5, telefono);
                pst.setString(6, cell);
                pst.setString(7, observaciones);
                pst.setString(8, mail);

                pst.executeUpdate();
                cn.close();

                Limpiar();

                jTextField_nombre.setBackground(Color.green);
                jTextField_apellido.setBackground(Color.green);
                jTextField_nacionalidad.setBackground(Color.green);
                jTextField_telefono.setBackground(Color.green);
                jTextField_cell.setBackground(Color.green);
                jTextField_mail.setBackground(Color.green);
                jTextArea_observaciones.setBackground(Color.green);

                JOptionPane.showMessageDialog(null, "Los datos se han ingresado correctamente");
                this.dispose();

            } catch (SQLException e) {
                System.err.println("Error en registrar cliente. " + e);
                JOptionPane.showMessageDialog(null, "!!Error al registrar cliente...contacte a su administrador.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debes llenar los campos nombre y apellido.");
        }
    }
    
}
