/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import clases.Conexion;
import java.sql.*;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author ALEX
 */
public class ContrasenaCambiar extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public ContrasenaCambiar() {
        initComponents();
        setSize(400, 550);
        setResizable(false);
        setTitle("Cambiar contraseña - " + Login.user);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);

    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/Icon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_logo = new javax.swing.JLabel();
        jPasswordField_confirmar_contrasena = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel_footer = new javax.swing.JLabel();
        jButton_cambiar = new javax.swing.JButton();
        jPasswordField_nueva_contrasena = new javax.swing.JPasswordField();
        jPasswordField_contrasena = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logo_fondoGrisII.png"))); // NOI18N
        jPanel1.add(jLabel_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 60, 150, 130));

        jPasswordField_confirmar_contrasena.setBackground(new java.awt.Color(204, 204, 204));
        jPasswordField_confirmar_contrasena.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPasswordField_confirmar_contrasena.setForeground(new java.awt.Color(0, 0, 115));
        jPasswordField_confirmar_contrasena.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPasswordField_confirmar_contrasena.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        jPasswordField_confirmar_contrasena.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField_confirmar_contrasenaKeyPressed(evt);
            }
        });
        jPanel1.add(jPasswordField_confirmar_contrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 375, 200, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Nueva contraseña");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 150, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Reconfirmar");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 405, 150, 25));

        jLabel_footer.setText("© Realizado por atstincer");
        jPanel1.add(jLabel_footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 500, 150, 20));

        jButton_cambiar.setBackground(new java.awt.Color(153, 153, 153));
        jButton_cambiar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_cambiar.setText("Cambiar");
        jButton_cambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cambiarActionPerformed(evt);
            }
        });
        jButton_cambiar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton_cambiarKeyPressed(evt);
            }
        });
        jPanel1.add(jButton_cambiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 455, -1, 30));

        jPasswordField_nueva_contrasena.setBackground(new java.awt.Color(204, 204, 204));
        jPasswordField_nueva_contrasena.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPasswordField_nueva_contrasena.setForeground(new java.awt.Color(0, 0, 115));
        jPasswordField_nueva_contrasena.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPasswordField_nueva_contrasena.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        jPanel1.add(jPasswordField_nueva_contrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 200, 30));

        jPasswordField_contrasena.setBackground(new java.awt.Color(204, 204, 204));
        jPasswordField_contrasena.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPasswordField_contrasena.setForeground(new java.awt.Color(0, 0, 115));
        jPasswordField_contrasena.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPasswordField_contrasena.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        jPanel1.add(jPasswordField_contrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 245, 200, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Contraseña");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 275, 150, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_cambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cambiarActionPerformed
        // TODO add your handling code here:
        ModificarContrasena();
    }//GEN-LAST:event_jButton_cambiarActionPerformed

    private void jButton_cambiarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton_cambiarKeyPressed
        // TODO add your handling code here:
        if(evt.getExtendedKeyCode()==KeyEvent.VK_ENTER){
           ModificarContrasena();
        }
    }//GEN-LAST:event_jButton_cambiarKeyPressed

    private void jPasswordField_confirmar_contrasenaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField_confirmar_contrasenaKeyPressed
        // TODO add your handling code here:
        if(evt.getExtendedKeyCode()==KeyEvent.VK_ENTER){
           ModificarContrasena();
        }
    }//GEN-LAST:event_jPasswordField_confirmar_contrasenaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContrasenaCambiar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContrasenaCambiar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContrasenaCambiar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContrasenaCambiar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContrasenaCambiar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_cambiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_footer;
    private javax.swing.JLabel jLabel_logo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField_confirmar_contrasena;
    private javax.swing.JPasswordField jPasswordField_contrasena;
    private javax.swing.JPasswordField jPasswordField_nueva_contrasena;
    // End of variables declaration//GEN-END:variables

    public void ModificarContrasena(){
        String contrasena = jPasswordField_contrasena.getText();
        String nueva_contrasena = jPasswordField_nueva_contrasena.getText();
        String confirmar_contrasena = jPasswordField_confirmar_contrasena.getText();

        if (!contrasena.equals("")) {
            try {
                Connection cn = Conexion.conectar();
                PreparedStatement pst = cn.prepareStatement("select Contrasena from usuarios where Usuario = "
                        + "'" + Login.user + "'");

                ResultSet rs = pst.executeQuery();

                if (rs.next()) {
                    String contrasena_hayada = rs.getString("Contrasena");
                    if (contrasena.equals(contrasena_hayada)) {
                        if (!nueva_contrasena.equals("") && !confirmar_contrasena.equals("")) {
                            if (nueva_contrasena.equals(confirmar_contrasena)) {
//                                try {
                                    pst = cn.prepareStatement("update usuarios set Contrasena = '" + nueva_contrasena + "'"
                                            + " where Usuario = '" + Login.user + "'");
                                    pst.executeUpdate();
                                    cn.close();
                                    JOptionPane.showMessageDialog(null, "Se cambió la contraseña correctamente.");
//                                } catch (SQLException e) {
//                                    JOptionPane.showMessageDialog(null, "Error comunicando con la BD.\n Contacte al administrador.");
//                                }
                                cn.close();
                                dispose();
                            } else {
                                JOptionPane.showMessageDialog(null, "La confirmación de la nueva contraseña "
                                        + "no coincide." + "\n" + ""
                                        + "Inténtelo de nuevo.");
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "Debe llenar todos los campos.");
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Su contraseña no coincide con la proporcionada."
                                + "" + "\n" + "Por favor, inténtelo de nuevo.");
                    }
                }
                cn.close();
            } catch (Exception e) {
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debes escribir tu contraseña.");
        }
    }
    
}
